import type { SourceCatalogEntry } from "./types";

export const SOURCE_CATALOG: SourceCatalogEntry[] = [
  {
    type: "github",
    name: "GitHub",
    blurb: "Repositories, releases, READMEs, languages, and merged pull requests.",
    live: true,
    auth: "oauth",
    fields: [
      {
        key: "accessToken",
        label: "Personal access token (optional if OAuth is configured)",
        secret: true,
        optional: true,
        placeholder: "ghp_… or github_pat_…",
      },
    ],
    apiNotes:
      "Official GitHub REST + Search APIs. OAuth scopes: read:user, user:email. Public repos need no extra repo scope. Private repos are not requested.",
  },
  {
    type: "gitlab",
    name: "GitLab",
    blurb: "Owned projects from gitlab.com via the official REST API.",
    live: true,
    auth: "token",
    fields: [
      { key: "accessToken", label: "Personal access token", secret: true, placeholder: "glpat-…" },
    ],
    apiNotes: "Official GitLab API v4. Token scope: read_api. Hosted gitlab.com in the MVP.",
  },
  {
    type: "npm",
    name: "npm",
    blurb: "Published packages attributed to your npm username.",
    live: true,
    auth: "public-id",
    fields: [{ key: "username", label: "npm username", placeholder: "your-handle" }],
    apiNotes: "Public npm registry search API. No OAuth. Only packages the registry attributes to that maintainer.",
  },
  {
    type: "pypi",
    name: "PyPI",
    blurb: "Python packages you name, read from the official project JSON API.",
    live: true,
    auth: "public-id",
    fields: [
      { key: "projects", label: "Project names (comma separated)", placeholder: "my-package, another-package" },
      { key: "username", label: "PyPI username (optional, for the profile link)", optional: true, placeholder: "your-handle" },
    ],
    apiNotes:
      "Official PyPI JSON API (/pypi/<project>/json). PyPI has no documented endpoint that lists a username’s projects — the profile page is HTML only — so projects are named explicitly rather than scraped. Ownership is not asserted by the API and is never claimed.",
  },
  {
    type: "devto",
    name: "Dev.to",
    blurb: "Published technical articles on Dev.to / Forem.",
    live: true,
    auth: "public-id",
    fields: [{ key: "username", label: "Dev.to username", placeholder: "your-handle" }],
    apiNotes: "Official Forem API. Public articles by username. An API key is not required for public posts.",
  },
  {
    type: "arxiv",
    name: "arXiv",
    blurb: "Preprints matching your author name.",
    live: true,
    auth: "public-id",
    fields: [{ key: "author", label: "Author name as used on arXiv", placeholder: "Ada Lovelace" }],
    apiNotes: "Official arXiv Atom API. Name matching can be ambiguous; results are marked uncertain when coauthors dominate.",
  },
  {
    type: "orcid",
    name: "ORCID",
    blurb: "Public works registered to your ORCID iD.",
    live: true,
    auth: "public-id",
    fields: [{ key: "orcid", label: "ORCID iD", placeholder: "0000-0000-0000-0000" }],
    apiNotes: "Official public ORCID API v3. Only public works. No OAuth required for public records.",
  },
  {
    type: "kaggle",
    name: "Kaggle",
    blurb: "Kernels/notebooks from the official Kaggle API.",
    live: true,
    auth: "token",
    fields: [
      { key: "username", label: "Kaggle username", placeholder: "handle" },
      { key: "apiKey", label: "API key from kaggle.json", secret: true },
    ],
    apiNotes:
      "Official Kaggle REST API with HTTP basic auth (username + API key). Competition leaderboard placement is not reliably exposed for an arbitrary user, so the MVP ingests kernels you authored. Rankings can be added later if Kaggle returns them for the authenticated account.",
  },
  {
    type: "hashnode",
    name: "Hashnode",
    blurb: "Restricted since May 2026. Import a post URL instead.",
    live: false,
    auth: "manual",
    fields: [],
    apiNotes:
      "Hashnode retired free GraphQL API access on 2026-05-13; reading now requires a paid Pro plan, and the unauthenticated endpoint redirects to their announcement. Rather than ship a connector that always fails, import the post URL manually.",
  },
  {
    type: "linkedin",
    name: "LinkedIn",
    blurb: "Publish portfolio items as LinkedIn posts. Reading your LinkedIn is not permitted by LinkedIn.",
    live: false,
    publish: true,
    auth: "oauth",
    fields: [],
    apiNotes:
      "Two-way is impossible here, and the asymmetry is LinkedIn’s, not ours. WRITING works: the self-serve “Share on LinkedIn” product grants w_member_social, so this app can publish an approved item to your feed (POST /rest/posts). READING does not: retrieving a member’s own posts requires r_member_social, which LinkedIn documents as restricted to approved partners, and Sign In with LinkedIn (OpenID Connect) returns only name, picture, locale, and email — no headline, positions, education, or skills. So LinkedIn history is captured through manual import, and LinkedIn is never scraped.",
  },
  {
    type: "devpost",
    name: "Devpost",
    blurb: "No public user API. Import a hackathon project with a link.",
    live: false,
    auth: "manual",
    fields: [],
    apiNotes: "Devpost does not provide a documented public API for a user’s hackathon history. Import the project URL and facts you can verify.",
  },
  {
    type: "notion",
    name: "Notion",
    blurb: "Coming later via official Notion OAuth. Import a page URL for now.",
    live: false,
    auth: "manual",
    fields: [],
    apiNotes: "Notion has an official OAuth API, but capability depends on which databases the user shares. Deferred to keep the MVP focused.",
  },
  {
    type: "gdrive",
    name: "Google Drive",
    blurb: "Certificates in Drive need OAuth + user-selected files. Import the credential instead.",
    live: false,
    auth: "manual",
    fields: [],
    apiNotes:
      "Google Drive has a real OAuth API, but scanning a whole drive for certificates is invasive and unreliable. MVP uses explicit credential import.",
  },
  {
    type: "youtube",
    name: "YouTube",
    blurb: "YouTube Data API is available; not in the first live set. Import a talk URL.",
    live: false,
    auth: "manual",
    fields: [],
    apiNotes: "YouTube Data API v3 can list a channel’s uploads with an API key or OAuth. Deferred.",
  },
  {
    type: "manual",
    name: "Manual evidence",
    blurb: "Certifications, awards, talks, and anything a platform will not expose.",
    live: true,
    auth: "manual",
    fields: [],
    apiNotes: "User-supplied facts only. The curator will not invent missing dates, ranks, or issuers.",
  },
];
